# Generated by Django 4.2.8 on 2024-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.CharField(max_length=10)),
                ('shopName', models.CharField(max_length=50)),
            ],
        ),
    ]
