# Generated by Django 4.2.8 on 2024-01-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Drinks', 'Drinks'), ('Furniture', 'Furniture')], default='Electronics', max_length=20),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.CharField(max_length=20)),
                ('offerprice', models.FloatField()),
                ('offeredby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.product')),
            ],
        ),
    ]
