# Generated by Django 4.2.8 on 2024-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_product_productcategory_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopContact',
            field=models.CharField(default='9999999999', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopOwner',
            field=models.CharField(default='Blank', max_length=50),
        ),
    ]
