# Generated by Django 4.2.8 on 2024-01-02 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0005_shop_shopcontact_shop_shopowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
