# Generated by Django 4.2.8 on 2024-01-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0008_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
