# Generated by Django 4.2.8 on 2024-01-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0010_shop_password_shop_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapp.shop'),
        ),
    ]
