# Generated by Django 4.2.8 on 2024-01-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0011_product_productowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.shop'),
        ),
    ]
