# Generated by Django 4.2.8 on 2024-01-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0014_alter_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='username',
        ),
    ]
