# Generated by Django 4.1 on 2024-01-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0015_remove_shop_password_remove_shop_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MallOwner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productOwner',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
