# Generated by Django 4.1 on 2024-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0017_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
