# Generated by Django 4.2.9 on 2024-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0018_offer_is_valid_offer_offertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
