# Generated by Django 4.2.9 on 2024-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0019_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='productImages/product_placeholder.png', null=True, upload_to='productImages/'),
        ),
    ]
