# Generated by Django 4.2.9 on 2024-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0020_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mallName', models.CharField(max_length=100)),
                ('mallAddress', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fence_radius', models.FloatField()),
            ],
        ),
    ]
