# Generated by Django 4.2.9 on 2024-01-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0021_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapp.mall'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='fence_radius',
            field=models.FloatField(default=500, help_text='Fence Radius in meters(m)'),
        ),
    ]
