# Generated by Django 4.2.9 on 2024-01-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0022_shop_mall_alter_mall_fence_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='geoapp.mall'),
        ),
    ]
