# Generated by Django 4.2.9 on 2024-02-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0023_alter_shop_mall'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('userdevice', models.CharField(blank=True, max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='geoapp.offer')),
            ],
        ),
    ]
