# Generated by Django 4.2.9 on 2024-03-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0024_offerimpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='detail_exp_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='dismissed_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='received_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
